### ISSUE TITLE
[Feature Request] Parse better

### ISSUE THREAD

**Issue by alxest** [Ailrun/coq-commenter#4]
I use a module named "TODOProof",
and when I use definition from there, (e.g. TODOProof.abcd)
coq-commenter recognizes this as a proof.

Simply checking that no other alphabet is in front of "Proof" keyword should be sufficient me.

**Comment by Ailrun** [comment]
Oh.... I missed that case.
I will fix this ASAP.
(Or, in the other words, when I can use my emacs development environment)

**Comment by Ailrun** [comment]
@alxest I fix this. At least I believe so.

Please update coq-commenter after its melpa version is updated.
